name: Create Multiple Repositories (Dominant Language Fixed)

on:
  workflow_dispatch:
    inputs:
      repo_count:
        description: 'Jumlah repository yang ingin dibuat'
        required: true
        default: 5
      dominant_lang:
        description: 'Bahasa pemrograman dominan'
        required: true
        default: python

jobs:
  create-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup variables
        run: |
          WORDS=("alpha" "beta" "gamma" "delta" "epsilon" "theta" "sigma" "nova" "quantum" "lumen" "orbit" "vector" "matrix" "core" "byte" "pixel" "neon")
          EXTRA=("project" "app" "service" "tool" "system" "engine" "platform" "framework")
          LANGS=("python" "cpp" "golang" "swift" "java" "javascript" "ruby")
          EXT=("py" "cpp" "go" "swift" "java" "js" "rb")
          CONTENTS=("print('im rixzstore')" "cout << 'im rixzstore';" "fmt.Println('im rixzstore')" "print('im rixzstore')" "System.out.println('im rixzstore');" "console.log('im rixzstore');" "puts 'im rixzstore'")

          echo "WORDS=${WORDS[*]}" >> $GITHUB_ENV
          echo "EXTRA=${EXTRA[*]}" >> $GITHUB_ENV
          echo "LANGS=${LANGS[*]}" >> $GITHUB_ENV
          echo "EXT=${EXT[*]}" >> $GITHUB_ENV
          echo "CONTENTS=${CONTENTS[*]}" >> $GITHUB_ENV

      - name: Create repositories
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          DOM_LANG: ${{ github.event.inputs.dominant_lang }}
        run: |
          IFS=' ' read -r -a WORDS <<< "$WORDS"
          IFS=' ' read -r -a EXTRA <<< "$EXTRA"
          IFS=' ' read -r -a LANGS <<< "$LANGS"
          IFS=' ' read -r -a EXT <<< "$EXT"
          IFS=' ' read -r -a CONTENTS <<< "$CONTENTS"

          COUNT=${{ github.event.inputs.repo_count }}
          declare -A USED_NAMES
          echo "Creating $COUNT repositories..."

          for i in $(seq 1 $COUNT); do
            # Nama repo realistis
            WORD_NUM=$((2 + RANDOM % 2))
            while true; do
              NAME=""
              for j in $(seq 1 $WORD_NUM); do
                NAME+="${WORDS[$RANDOM % ${#WORDS[@]}]}-"
              done
              NAME+="${EXTRA[$RANDOM % ${#EXTRA[@]}]}"
              NAME=$(echo "$NAME" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-')
              if [[ -z "${USED_NAMES[$NAME]}" ]]; then
                USED_NAMES[$NAME]=1
                break
              fi
            done

            # Pilih bahasa: dominan atau random
            if (( RANDOM % 2 == 0 )); then
              LANG=$DOM_LANG
              for idx in "${!LANGS[@]}"; do
                [[ "${LANGS[$idx]}" == "$DOM_LANG" ]] && FILE_EXT=${EXT[$idx]} && FILE_CONTENT=${CONTENTS[$idx]}
              done
            else
              INDEX=$((RANDOM % ${#LANGS[@]}))
              LANG=${LANGS[$INDEX]}
              FILE_EXT=${EXT[$INDEX]}
              FILE_CONTENT=${CONTENTS[$INDEX]}
            fi

            FILE_NAME="main.${FILE_EXT}"

            echo "Creating repo $NAME with $FILE_NAME ($LANG)"

            # Buat repo via API
            DATA=$(jq -n --arg name "$NAME" '{"name":$name,"auto_init":true}')
            curl -s -H "Authorization: token $PAT_TOKEN" \
                 -H "Accept: application/vnd.github+json" \
                 -d "$DATA" \
                 https://api.github.com/user/repos

            # Clone repo
            git clone https://$PAT_TOKEN@github.com/${{ github.repository_owner }}/$NAME.git
            cd $NAME

            git config user.name "GitHub Actions Bot"
            git config user.email "actions@github.com"

            # Buat file dominan cukup besar supaya GitHub mendeteksi bahasa
            for n in {1..20}; do
              echo "$FILE_CONTENT" >> $FILE_NAME
            done

            git add $FILE_NAME
            git commit -m "Add initial file $FILE_NAME"
            git push origin main

            cd ..
            rm -rf $NAME
          done
